### ISSUE TITLE
`{errors: "Could not find query-engine binary. Searched in /v…e_modules/@prisma/query-engine-rhel-openssl-1.0.x", type: 1}`

### ISSUE THREAD

**Issue by janpio** [Ovyerus/prismaliser#1]
Current deployment:
![image](https://user-images.githubusercontent.com/183673/127012381-75b64b43-aa13-412b-a059-049ee76119d9.png)

(Let me know if we from Prisma can help in any way)

**Comment by Ovyerus** [comment]
I opened a corresponding issue at prisma/prisma#8441, I don't *think* there's anything I can do on my end, I've tried changing the SDK version, disabling Webpack 5, marking it as an external, and nothing's seemed to have worked yet.

**Comment by Ovyerus** [comment]
Fixed in 01386ef64a3d4a90878a3a2d2153a87f03b9f408 thanks to a solution from the Prisma team! 🎉
