### ISSUE TITLE
CodeMirror: Monaco alternative

### ISSUE THREAD

**Issue by ruheni** [Ovyerus/prismaliser#21]
Hey Michael, if you're looking to swap out Monaco for something else, you can take a look at CodeMirror and https://github.com/prisma/text-editors (uses codemirror under the hood). I wasn't involved in the building process but I'd be happy to take a stab at this issue too.

**Comment by Ovyerus** [comment]
Thanks for the suggestion Alex, will check it out when I can. `@prisma/text-editors` looks interesting!

**Comment by Ovyerus** [comment]
Finally got around to testing CodeMirror/`@prisma/text-editors` but I don't think it'll work right for Prismaliser.

- Prisma syntax highlighting (not embedded in TS or JS) doesn't work when I tried (maybe even just doesn't exist?).
- No custom error markers so errors experience would be downgraded.
- No autocomplete without extending it I assume (can't even get a different CodeMirror autocomplete example working
- General UI shmutz, not a fan of how it looks (text selection mostly), subjective ik but it's my project :p

I think I'll just end up sticking with Monaco and working around some of its iffyness. Thanks for the suggestion though!
