### ISSUE TITLE
Feature to export the preview as image

### ISSUE THREAD

**Issue by lallenfrancisl** [Ovyerus/prismaliser#26]
It would be really nice if we could export the preview as an image. This could have usecases where we want to store it as documentation or include it in a website

**Comment by Ovyerus** [comment]
Definitely would be cool to have, a good idea. [React Flow](https://reactflow.dev/) (the graph lib I'm using) doesn't seem to have a screenshot capability. However I notice [monkeytype](https://monkeytype.com/) seems to take a screenshot of the results element (it changes temporarily to match what it has in the screenshot, before reverting back), so I'll do some digging to see if I can pull it off and implement something similar here.

**Comment by guatedude2** [comment]
Have you I saw @dravorle added the screenshot functionality. Is this something that's coming to the hosted version anytime soon?

**Comment by Ovyerus** [comment]
Yes I'll be getting it out to the hosted version as soon as I can. Noticed some weirdness with it (flow not going back to its normal size, and weird output size) during some testing yesterday though so I'm going to be changing some parts of it to try and fix it.

**Comment by dravorle** [comment]
Just tested it and somehow there are really quite a few weird things with it now. 
It might be due to the update to react flow 11, as I have not worked with that version when writing it.

Sorry for the complications!

**Comment by Ovyerus** [comment]
No worries, it was good to get the ball rolling at least.
