### ISSUE TITLE
Support for CockroachDB datasource provider

### ISSUE THREAD

**Issue by adamjq** [Ovyerus/prismaliser#48]
CockroachDB is a supported Prisma database provider: https://www.prisma.io/docs/concepts/database-connectors/cockroachdb

However, loading a CockroachDB Prisma schema into Prismaliser gives an error saying it's not known:

<img width="461" alt="cockroachdb_error" src="https://user-images.githubusercontent.com/20121496/197697128-927234ef-9081-4faa-b045-1c8165036bb2.png">

Similarly, Cockroach functions such as `sequence()` don't appear to be supported either:

<img width="485" alt="sequence_error" src="https://user-images.githubusercontent.com/20121496/197697220-c59c1c19-b3e7-4a50-b1ad-d506fe25662c.png">

It'd be great to eventually add support for Cockroach schemas to Prismaliser. Love the project

**Comment by Ovyerus** [comment]
Should be fixed in the beta branch at https://dev.prismaliser.app. Will try to get this out to production asap

**Comment by Ovyerus** [comment]
In production now.
