### ISSUE TITLE
Feature idea: VSCode extension

### ISSUE THREAD

**Issue by thawankeane** [Ovyerus/prismaliser#55]
It would be really nice if there was an extension to VSCode that could open a prisma schema preview using prismaliser, like the [built-in markdown previewer](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview) of vscode or other extensions like [draw.io
](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio)

I don't know if this would be in the scope of the project, but it seems like a cool idea.

**Comment by Ovyerus** [comment]
Yeah that's a cool idea, but is out of the scope of this project IMO. Wouldn't be against it being done by someone else though.
