### ISSUE TITLE
One to Many Relationship Backwards

### ISSUE THREAD

**Issue by mpmccauley** [Ovyerus/prismaliser#57]
In the visualizer, the crows feet point to the "one" instead of pointing to the "many".

```
model Person {
  id      Int       @id @default(autoincrement())
  friends Friends[]
}

model Friends {
  id       Int     @id @default(autoincrement())
  Person   Person? @relation(fields: [personId], references: [id])
  personId Int?
}
```

![image](https://user-images.githubusercontent.com/9283692/233183847-03b535a3-b265-49af-b324-52c9c9f5e6a6.png)

Shouldn't it be the other way around?

**Comment by Ovyerus** [comment]
Nope, from all I've seen, the way it's currently done in Prismaliser is correct

![Entity relation diagram, consisting of several one-to-many relationships](https://cdn-images.visual-paradigm.com/guide/data-modeling/what-is-erd/01-entity-relationship-diagram.png)

**Comment by mpmccauley** [comment]
Welp, TIL. Seems backwards to me but I'll go with it. I like the tool a lot.

**Comment by Sedhupathi1411** [comment]
Hey, I also have the same doubt.
I used dbdiagram.io before.
So, for me the Mapping seems to be reversed.
I would like to know if my presumption was wrong.

I've attached one example from dbdiagram.io where one country can have many users (one-to-many):-
![image](https://github.com/Ovyerus/prismaliser/assets/53770337/cc1ac18d-7f6a-412e-a1fd-8ef7d7e24e66)
