### ISSUE TITLE
Possible to feed my local schema file?

### ISSUE THREAD

**Issue by beshur** [Ovyerus/prismaliser#64]
Hi!

I didn't get if it's possible to feed my local schema file when launching visualizer or even better when udpates in preview and locally are synced?

**Comment by beshur** [comment]
Did a small script to do it https://gist.github.com/beshur/41a15c0272454373fd07ba9fbc6dfd5d

**Comment by Ovyerus** [comment]
There's no way to do that, Prismaliser is more aimed at being a general purpose web-app rather than a local tool, but that might be something to consider for the future.

**Comment by beshur** [comment]
Thanks, but I really liked to use it locally (with the script above).

I just added it in my npm scripts, and call it up whenever I need to look at the structure. 

Great project, thanks!
