### ISSUE TITLE
in next.js 13.4.13, an error saying Error: Invariant: Expected relative import to start with "next/", found "_next@13.4.13@next/dist/server/future/route-kind

### ISSUE THREAD

**Issue by helxsz** [Ovyerus/prismaliser#69]
i install the app but running with an error saying 
**'Error: Invariant: Expected relative import to start with "next/", found "_next@13.4.13@next/dist/server/future/route-kind"'**

It looks like the version compatibility with next.js 13.4.13. When the next.js version rolls back to 13.4.8, it works well.

But just wondering, how would I modify the code in order to make it adapt to the latest next.js version

**Comment by Ovyerus** [comment]
Hey there, sorry about the super late response. I've bumped all the dependencies including Next.js and I'm not seeing this occur locally, are you able to confirm that it's been fixed on your side on the latest commit?
