### ISSUE TITLE
Please add Fullscreen mode or sidebar collups expandable

### ISSUE THREAD

**Issue by shourovr82** [Ovyerus/prismaliser#73]

**Comment by salimalsazu** [comment]
need it asap :)

**Comment by Ovyerus** [comment]
There are plans to do a redesign once I've finished up #45/#63, and this has been floating around as an idea so I think I'll do this.

**Comment by shourovr82** [comment]
> There are plans to do a redesign once I've finished up #45/#63, and this has been floating around as an idea so I think I'll do this.

Advance Thanks :-;
