### ISSUE TITLE
 Feature: Implement html2canvas to save the diagram to a image

### ISSUE THREAD

**Issue by CsarChvz** [Ovyerus/prismaliser#76]
Add a button to save the diagram into a image

**Comment by Ovyerus** [comment]
Duplicate of #26

**Comment by sharifmrahat** [comment]
Download diagram option is not available. Can follow the react-follow docs: https://reactflow.dev/examples/misc/download-image

**Comment by Ovyerus** [comment]
This is now implemented as of 3758d6fbe30ac20b99be50f13e4ebf79d266e521
